import { Course, Note, StudyGoal, TimetableEntry } from "./storage";

export const AVAILABLE_COURSES: Course[] = [
  {
    id: "1",
    name: "Introduction to Computer Science",
    code: "CS101",
    category: "Computer Science",
    description: "Fundamentals of programming and algorithms",
    lecturerName: "Dr. Sarah Johnson",
  },
  {
    id: "2",
    name: "Data Structures and Algorithms",
    code: "CS201",
    category: "Computer Science",
    description: "Advanced data structures and algorithm design",
    lecturerName: "Prof. Michael Chen",
  },
  {
    id: "3",
    name: "Calculus I",
    code: "MATH101",
    category: "Mathematics",
    description: "Differential and integral calculus",
    lecturerName: "Dr. Emily Watson",
  },
  {
    id: "4",
    name: "Linear Algebra",
    code: "MATH201",
    category: "Mathematics",
    description: "Vector spaces and linear transformations",
    lecturerName: "Prof. David Lee",
  },
  {
    id: "5",
    name: "Physics I",
    code: "PHY101",
    category: "Physics",
    description: "Classical mechanics and thermodynamics",
    lecturerName: "Dr. Robert Miller",
  },
  {
    id: "6",
    name: "Organic Chemistry",
    code: "CHEM201",
    category: "Chemistry",
    description: "Structure and reactions of organic compounds",
    lecturerName: "Dr. Lisa Anderson",
  },
  {
    id: "7",
    name: "Business Management",
    code: "BUS101",
    category: "Business",
    description: "Principles of business and management",
    lecturerName: "Prof. James Wilson",
  },
  {
    id: "8",
    name: "English Literature",
    code: "ENG201",
    category: "Literature",
    description: "Classic and modern English literature",
    lecturerName: "Dr. Amanda Brown",
  },
];

export const SAMPLE_NOTES: Note[] = [
  {
    id: "1",
    title: "Introduction to Programming Concepts",
    courseId: "1",
    courseName: "Introduction to Computer Science",
    fileType: "pdf",
    fileUri: "",
    uploadedBy: "Dr. Sarah Johnson",
    uploadedAt: "2024-01-15",
    size: "2.4 MB",
  },
  {
    id: "2",
    title: "Variables and Data Types",
    courseId: "1",
    courseName: "Introduction to Computer Science",
    fileType: "pdf",
    fileUri: "",
    uploadedBy: "Dr. Sarah Johnson",
    uploadedAt: "2024-01-18",
    size: "1.8 MB",
  },
  {
    id: "3",
    title: "Binary Trees and Traversal",
    courseId: "2",
    courseName: "Data Structures and Algorithms",
    fileType: "pdf",
    fileUri: "",
    uploadedBy: "Prof. Michael Chen",
    uploadedAt: "2024-01-20",
    size: "3.1 MB",
  },
  {
    id: "4",
    title: "Limits and Continuity",
    courseId: "3",
    courseName: "Calculus I",
    fileType: "doc",
    fileUri: "",
    uploadedBy: "Dr. Emily Watson",
    uploadedAt: "2024-01-22",
    size: "1.5 MB",
  },
  {
    id: "5",
    title: "Matrix Operations",
    courseId: "4",
    courseName: "Linear Algebra",
    fileType: "pdf",
    fileUri: "",
    uploadedBy: "Prof. David Lee",
    uploadedAt: "2024-01-25",
    size: "2.0 MB",
  },
];

export const SAMPLE_STUDY_GOALS: StudyGoal[] = [
  {
    id: "1",
    title: "Complete CS101 Assignment",
    targetHours: 10,
    completedHours: 7,
    deadline: "2024-02-01",
  },
  {
    id: "2",
    title: "Review Calculus Notes",
    targetHours: 5,
    completedHours: 2,
    deadline: "2024-01-30",
  },
  {
    id: "3",
    title: "Prepare for Physics Exam",
    targetHours: 15,
    completedHours: 10,
    deadline: "2024-02-05",
  },
];

export const SAMPLE_TIMETABLE: TimetableEntry[] = [
  {
    id: "1",
    courseId: "1",
    courseName: "CS101",
    day: "Monday",
    startTime: "09:00",
    endTime: "10:30",
    location: "Room 101",
  },
  {
    id: "2",
    courseId: "3",
    courseName: "MATH101",
    day: "Monday",
    startTime: "11:00",
    endTime: "12:30",
    location: "Room 205",
  },
  {
    id: "3",
    courseId: "2",
    courseName: "CS201",
    day: "Tuesday",
    startTime: "14:00",
    endTime: "15:30",
    location: "Lab 3",
  },
  {
    id: "4",
    courseId: "4",
    courseName: "MATH201",
    day: "Wednesday",
    startTime: "10:00",
    endTime: "11:30",
    location: "Room 302",
  },
  {
    id: "5",
    courseId: "5",
    courseName: "PHY101",
    day: "Thursday",
    startTime: "09:00",
    endTime: "10:30",
    location: "Physics Lab",
  },
];

export const LIVE_CLASSES = [
  {
    id: "1",
    courseId: "1",
    courseName: "Introduction to Computer Science",
    lecturerName: "Dr. Sarah Johnson",
    topic: "Control Flow and Loops",
    isLive: true,
    participants: 45,
    startTime: "10:00 AM",
  },
  {
    id: "2",
    courseId: "2",
    courseName: "Data Structures and Algorithms",
    lecturerName: "Prof. Michael Chen",
    topic: "Graph Algorithms",
    isLive: false,
    participants: 0,
    scheduledTime: "2:00 PM",
  },
  {
    id: "3",
    courseId: "3",
    courseName: "Calculus I",
    lecturerName: "Dr. Emily Watson",
    topic: "Integration Techniques",
    isLive: false,
    participants: 0,
    scheduledTime: "4:00 PM",
  },
];
